version: "3.9"
services:
  api:
    build:
      context: ../../
      dockerfile: code/deployment/api/Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/model.joblib

  app:
    build:
      context: ../../
      dockerfile: code/deployment/app/Dockerfile
    container_name: app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
